#/bin/bash
code --install-extension abusaidm.html-snippets
code --install-extension Angular.ng-template
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension ghaschel.vscode-angular-html
code --install-extension Gruntfuggly.todo-tree
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension nrwl.angular-console
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension steoates.autoimport
code --install-extension vscjava.vscode-java-debug
