#/bin/bash
code --install-extension abusaidm.html-snippets
code --install-extension Angular.ng-template
code --install-extension bradgashler.htmltagwrap
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension GregorBiswanger.json2ts
code --install-extension Gruntfuggly.todo-tree
code --install-extension humao.rest-client
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.Angular2
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mushan.vscode-paste-image
code --install-extension oderwat.indent-rainbow
code --install-extension Pivotal.vscode-boot-dev-pack
code --install-extension Pivotal.vscode-spring-boot
code --install-extension pmneo.tsimporter
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension sandcastle.vscode-open
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension stringham.move-ts
code --install-extension vector-of-bool.gitflow
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wmaurer.change-case
code --install-extension Zaczero.bootstrap-v4-snippets
