#/bin/bash
code --install-extension 1tontech.angular-material
code --install-extension 74th.monokai-charcoal-high-contrast
code --install-extension abusaidm.html-snippets
code --install-extension ACharLuk.easy-cpp-projects
code --install-extension Angular.ng-template
code --install-extension AngularDoc.angulardoc-vscode
code --install-extension batisteo.vscode-django
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cyrilletuzi.angular-schematics
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension dirk-thomas.vscode-lark
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension efbenson.scad
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Monokai-Contrast
code --install-extension ghaschel.vscode-angular-html
code --install-extension GregorBiswanger.json2ts
code --install-extension Gruntfuggly.todo-tree
code --install-extension hars.CppSnippets
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension magicstack.MagicPython
code --install-extension MarinhoBrandao.Angular2Tests
code --install-extension Mikael.Angular-BeastCode
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension NG-42.ng-fortytwo-vscode-extension
code --install-extension nrwl.angular-console
code --install-extension PKief.material-icon-theme
code --install-extension platformio.platformio-ide
code --install-extension pmneo.tsimporter
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension rockcat.avr-support
code --install-extension sandcastle.vscode-open
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension SimonTest.simontest
code --install-extension stringham.move-ts
code --install-extension twxs.cmake
code --install-extension UVBrain.Angular2
code --install-extension vector-of-bool.cmake-tools
code --install-extension vector-of-bool.gitflow
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wgenial.html-snippets
code --install-extension wholroyd.jinja
code --install-extension wmaurer.change-case
